import { readFileSync, writeFileSync } from 'fs';

var c = readFileSync('index.html', 'utf8');

// Find the insert point - before the closing ]; of NAI_KB
var marker = '    ];\n\n    /* ---- answer engine ---- */';
var idx = c.indexOf(marker);
if (idx === -1) { console.log('ERROR: insert point not found'); process.exit(1); }

var newEntries = `      { id: "exam-system", topics: ["exam system", "semester system", "level term", "exam schedule", "exam procedure", "in-course exam", "final exam", "how are exams conducted", "exam pattern", "term exam"],
        a: "NITER uses a Level-Term examination system under the University of Dhaka. Each academic year has two semesters (terms), with fixed credits per semester. The B.Sc. in Textile Engineering spans 4 years across 8 semesters/levels (L1-T1 to L4-T2).\\n\\nExam Types:\\n1. In-Course (Class Test / CT):\\n- Conducted during the semester by course teachers\\n- Typically 2-3 class tests per course\\n- Marks usually 20-30% of total course marks\\n- Covers topics taught since the last CT\\n\\n2. Sessional / Lab Exam:\\n- Practical and lab-based examinations\\n- Conducted by internal examiners and external moderators\\n- Includes lab viva, experiments, and project evaluations\\n\\n3. Final Examination:\\n- Written theory exam at the end of each term\\n- Duration: typically 1-2 hours per subject\\n- Conducted by the Office of the Examinations\\n- Questions prepared by departmental exam committees\\n\\n4. Comprehensive Viva / Oral Exam:\\n- Final year comprehensive viva voce\\n- Covers entire program curriculum\\n- Conducted by a panel of examiners\\n\\nExam Schedule: Exams are officially scheduled by the Office of the Examinations and published on the NITER notice board and ERP system. Term-1 2024 exams ran from April 2 to April 21, 2025.\\n\\nFor exam schedules and notices, check niter.edu.bd or the ERP system.", link: { href: "https://niter.edu.bd/offices/office-of-the-examinations/", label: "Office of the Examinations" } },

      { id: "exam-office", topics: ["exam office", "controller of examinations", "exam controller", "deputy controller", "Ahmed Iqbal Reza", "examoffice", "exam office contact"],
        a: "Office of the Examinations at NITER:\\n\\nHead: Ahmed Iqbal Reza\\n- Designation: Deputy Controller of Examinations and Head\\n- Email: aireza@niter.edu.bd\\n- Phone: 01611470612\\n\\nSection Officer: Md. Rejoanul Islam\\n- Email: rislam@niter.edu.bd\\n- Phone: 01740018359\\n\\nContact:\\n- Email: examoffice@niter.edu.bd\\n- Phone: +880 1816 771 340\\n\\nOffice Hours: Sunday-Thursday (NITER working days)\\n\\nResponsibilities:\\n- Publishing exam schedules and seat plans\\n- Managing exam registration and enrollment\\n- Coordinating exam committees for each department\\n- Ensuring proper question setting, moderation, and printing\\n- Publishing exam results and transcripts\\n- Managing grade appeals and retake exams\\n- Coordinating with department heads on exam procedures\\n\\nFor any exam-related queries, visit the Examinations Office or email examoffice@niter.edu.bd.", link: { href: "https://niter.edu.bd/offices/office-of-the-examinations/", label: "Visit Exam Office page" } },

      { id: "exam-committee", topics: ["exam committee", "question setter", "moderator", "chief examiner", "exam committee chairman", "exam committee members"],
        a: "NITER Exam Committee System:\\n\\nEach department at NITER forms an Examination Committee for every term/semester. The committee is responsible for the entire examination process.\\n\\nExam Committee Structure:\\n- Chairman: Usually the Department Head or a senior professor\\n- Question Setters: Faculty members who prepare exam questions\\n- Moderators: Senior faculty who review and moderate questions for difficulty and coverage\\n- Chief Examiner: Oversees the marking process\\n- Panel of Examiners: Faculty who evaluate answer scripts\\n\\nResponsibilities of the Exam Committee:\\n1. Preparing the exam schedule and distributing to students\\n2. Selecting question setters for each course\\n3. Ensuring questions cover the syllabus properly\\n4. Moderating questions to maintain quality and fairness\\n5. Setting marking schemes and answer keys\\n6. Coordinating external examiners for lab/sessional exams\\n7. Overseeing proper conduct of examinations\\n8. Reviewing and finalizing results\\n9. Preparing the comprehensive viva panel\\n\\nDepartment-specific committees exist for:\\n- Textile Engineering (TE)\\n- Computer Science and Engineering (CSE)\\n- Electrical and Electronic Engineering (EEE)\\n- Industrial and Production Engineering (IPE)\\n- Fashion Design and Apparel Engineering (FDAE)\\n\\nStudents can contact their department office for committee details and exam schedules.", link: null },

      { id: "mark-distribution", topics: ["mark distribution", "grading system", "CGPA", "pass mark", "grade point", "how marks are calculated", "sessional marks", "class test marks", "final exam marks", "attendance marks"],
        a: "NITER Mark Distribution and Grading System (University of Dhaka Pattern):\\n\\nMark Distribution (typical per course):\\n1. Sessional / In-Course Assessment: 40%\\n   - Class Tests (CT): 20-25%\\n   - Attendance: 5-10%\\n   - Assignments/Presentations: 5-10%\\n   - Lab/Practical: varies by course\\n\\n2. Final Examination: 60%\\n   - Written theory exam\\n   - Covers entire term syllabus\\n\\nTotal per course: 100 marks (combined sessional + final)\\n\\nGrading Scale (4.0 scale, University of Dhaka):\\n- A+ = 4.00 (80-100%)\\n- A  = 3.75 (75-79%)\\n- A- = 3.50 (70-74%)\\n- B+ = 3.25 (65-69%)\\n- B  = 3.00 (60-64%)\\n- B- = 2.75 (55-59%)\\n- C+ = 2.50 (50-54%)\\n- C  = 2.25 (45-49%)\\n- D  = 2.00 (40-44%)\\n- F  = 0.00 (Below 40% = Fail)\\n\\nCGPA Classification:\\n- CGPA 3.00-4.00 = First Class\\n- CGPA 2.25-2.99 = Second Class\\n- CGPA 2.00-2.24 = Third Class\\n\\nPassing Requirements:\\n- Minimum 40% in each course (D grade)\\n- Must pass both sessional and final separately in some courses\\n- Minimum CGPA 2.00 to graduate\\n\\nAttendance Policy:\\n- Minimum 75% attendance required per course\\n- Below 75% may result in detention or NG (No Grade)\\n\\nFor exact mark distribution of your specific course, check the course syllabus or ask your course teacher.", link: { href: "https://niter.edu.bd/faq/", label: "NITER FAQ page" } },

      { id: "exam-quality", topics: ["question quality", "exam question pattern", "question paper quality", "how are questions set", "exam preparation tips", "previous year questions"],
        a: "NITER Question Pattern and Quality:\\n\\nQuestion Types:\\n1. Short Answer Questions (SAQ):\\n   - Typically 2-5 marks each\\n   - Tests definition, formulae, and brief explanations\\n   - Example: Define fiber, State types of yarn\\n\\n2. Long Answer / Essay Questions:\\n   - Typically 10-15 marks each\\n   - Tests in-depth understanding and analysis\\n   - Requires diagrams, calculations, or detailed explanations\\n\\n3. Multiple Choice Questions (MCQ):\\n   - Used in some courses and entrance exams\\n   - 100 MCQs covering Physics, Chemistry, Math, English (for admission)\\n\\n4. Numerical / Problem-Solving Questions:\\n   - Calculation-based questions\\n   - Tests application of formulas and engineering concepts\\n\\n5. Practical / Viva Questions:\\n   - Lab-based and oral examination\\n   - Tests hands-on skills and conceptual clarity\\n\\nQuestion Setting Process:\\n1. Course teacher (question setter) prepares the draft paper\\n2. Exam Committee moderator reviews for quality and coverage\\n3. Questions are checked for difficulty balance\\n4. Final version is approved and printed\\n\\nTips for Exam Preparation:\\n- Review previous years question papers (ask seniors or department library)\\n- Focus on core concepts, not just memorization\\n- Practice numerical problems regularly\\n- Attend all classes for sessional marks\\n- Take class tests seriously as they build exam skills\\n- Form study groups for complex topics\\n\\nPrevious year question papers are sometimes available from the department library, seniors, or NITER student forums.", link: null },

`;

c = c.substring(0, idx) + newEntries + c.substring(idx);
writeFileSync('index.html', c, 'utf8');
console.log('OK: Added 5 exam system KB entries');
